{{- if .Values.gangway.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: values-yaml
  namespace: {{ .Values.gangway.namespace }}
stringData:
  values.yaml: |-
    gangway:
      clientSecret: {{ .Values.dex.oauth.clientSecret | quote }}
      sessionKey: {{ include "moondog.random32" .Values.gangway.sessionKey | b64enc | quote }}
{{- end }}
