{{- if and .Values.certManager.create .Values.certManager.dns.route53.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dns-route53-credentials
  namespace: {{ .Values.certManager.namespace }}
data:
  AWS_SECRET_ACCESS_KEY: {{ .Values.certManager.dns.route53.accessKeySecret | b64enc | quote }}
{{- end }}
