{{- if .Values.certManager.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.certManager.namespace }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: {{ .Values.certManager.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.certManager.releaseName }}
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.13.0
  values:
    replicaCount: {{ .Values.certManager.replicaCount }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
{{- if .Values.certManager.dns.route53.create }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.domainSuffix }}
        dns01:
          route53:
            region: {{ .Values.certManager.dns.route53.region }}
            accessKeyID: {{ .Values.certManager.dns.route53.accessKeyId }}
            secretAccessKeySecretRef:
              name: dns-route53-credentials
              key: AWS_SECRET_ACCESS_KEY
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns-staging
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - selector:
          dnsZones:
            - {{ .Values.domainSuffix }}
        dns01:
          route53:
            region: {{ .Values.certManager.dns.route53.region }}
            accessKeyID: {{ .Values.certManager.dns.route53.accessKeyId }}
            secretAccessKeySecretRef:
              name: dns-route53-credentials
              key: AWS_SECRET_ACCESS_KEY
{{- end }}
{{- end }}
