{{- if and .Values.harbor.create .Values.kubedb.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-init-sql
  namespace: {{ .Values.harbor.namespace }}
data:
  harbor.sql: |
    CREATE DATABASE registry;
    CREATE DATABASE harbor;
    CREATE DATABASE core;
    CREATE DATABASE clair;
    CREATE DATABASE notary_server;
    CREATE DATABASE notary_signer;
{{- end }}