{{- if and .Values.harbor.create .Values.kubedb.create }}
apiVersion: v1
kind: Secret
metadata:
  name: harbor-db-auth
  namespace: {{ .Values.harbor.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.harbor.postgres.password | b64enc | quote }}
  POSTGRES_USER: {{ "postgres" | b64enc | quote }}
{{- end }}
