{{- if and .Values.harbor.create .Values.kubedb.create .Values.harbor.dbBackups.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ .Values.harbor.namespace }}
type: Opaque
data:
  {{- with .Values.harbor.dbBackups.credentials }}
  AWS_ACCESS_KEY_ID: {{ .accessKeyId | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .secretAccessKey | b64enc | quote }}
  {{- end }}
{{- end }}
