{{- if .Values.harbor.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: values-yaml
  namespace: {{ .Values.harbor.namespace }}
stringData:
  values.yaml: |-
    harborAdminPassword: {{ default (randAlphaNum 32) .Values.harbor.adminPassword | quote }}
    secretKey: {{ include "moondog.random16" .Values.harbor.secretKey | quote }}
    persistence:
      {{- with .Values.harbor.persistence.imageChartStorage}}
      imageChartStorage: {{- toYaml . | nindent 8}}
      {{- else }}
      imageChartStorage: {}
      {{- end }}
    database:
      external:
        password: {{ .Values.harbor.postgres.password | quote }}
{{- end }}