{{- if .Values.harbor.create }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: {{ .Values.harbor.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.harbor.releaseName }}
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.3.1
  valuesFrom:
    - secretKeyRef:
        name: values-yaml
  values:
    expose:
      ingress:
        hosts:
          core: harbor.{{ .Values.domainSuffix }}
          notary: harbor-notary.{{ .Values.domainSuffix }}
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: {{ .Values.certManager.defaultClusterIssuer | quote }}
      tls:
        notarySecretName: tls-harbor-notary-ingress
        secretName: tls-harbor-ingress
    externalURL: https://harbor.{{ .Values.domainSuffix }}
    database:
      type: external
      external:
        host: harbor-pg
        username: "postgres"
    redis:
      type: external
      external:
        host: {{ .Values.harbor.releaseName }}-redis-redis-ha-haproxy
{{- end }}
