{{- if .Values.sealedSecrets.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.sealedSecrets.namespace }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets-controller
  namespace: {{ .Values.sealedSecrets.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.sealedSecrets.releaseName }}
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: sealed-secrets
    version: 1.7.6
  values:
    rbac:
      pspEnabled: true

{{- end }}
