{{- if .Values.velero.create }}
apiVersion: v1
kind: Secret
metadata:
  name: velero-aws-credentials
  namespace: {{ .Values.velero.namespace }}
type: Opaque
data:
  cloud: {{ .Values.velero.awsCredentials }}
{{- end }}
