{{- if .Values.dex.create }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dex
  namespace: {{ .Values.dex.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.dex.releaseName }}
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: dex
    version: 2.10.0
  valuesFrom:
    - secretKeyRef:
        name: values-yaml
  values:
    grpc: false
    ports:
      web:
        nodePort: {{ .Values.dex.port }}
        servicePort: {{ .Values.dex.port }}
    config:
      issuer: https://dex.{{ .Values.domainSuffix }}
      enablePasswordDB: false
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: {{ .Values.certManager.defaultClusterIssuer | quote }}
      hosts:
        - dex.{{ .Values.domainSuffix }}
      tls:
        - secretName: dex-tls
          hosts:
            - dex.{{ .Values.domainSuffix }}
{{- end }}
