{{- if .Values.prometheusOperator.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: values-yaml
  namespace: {{ .Values.prometheusOperator.namespace }}
stringData:
  values.yaml: |-
    grafana:
      adminPassword: {{ .Values.prometheusOperator.grafana.adminPassword | quote }}
      grafana.ini:
        auth.generic_oauth:
          client_secret: {{ .Values.prometheusOperator.grafana.oauth.clientSecret | quote }}
{{- end }}
