{{- if .Values.prometheusOperator.create }}
apiVersion: v1
kind: Secret
metadata:
  name: etcd-client
  namespace: {{ .Values.prometheusOperator.namespace }}
data:
  ca.crt: {{ .Values.pki.etcd.ca.crt | b64enc |  quote }}
  healthcheck-client.key: {{ .Values.pki.etcd.healthcheckClient.key | b64enc | quote }}
  healthcheck-client.crt: {{ .Values.pki.etcd.healthcheckClient.crt | b64enc | quote }}
{{- end }}
