{{- if .Values.oauth2Proxy.create }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: values-yaml
  namespace: {{ .Values.oauth2Proxy.namespace }}
stringData:
  values.yaml: |-
    config:
      clientSecret: {{ .Values.oauth2Proxy.oauth.clientSecret | quote }}
      cookieSecret: {{ include "moondog.random32" .Values.oauth2Proxy.oauth.cookieSecret | b64enc | quote }}
{{- end }}
