{{- if .Values.flux.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.flux.envSecretName }}
  namespace: {{ .Values.flux.namespace }}
data:
  identity: {{ .Values.flux.git.auth.key }}
{{- end }}