{{- if .Values.flux.create }}
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: {{ .Values.flux.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.flux.releaseName }}
  chart:
    repository: https://charts.fluxcd.io/
    name: flux
    version: 1.3.0
  values:
    git:
      url: {{ .Values.flux.git.repo | quote }}
      branch: {{ .Values.flux.git.branch }}
      secretName: {{ .Values.flux.envSecretName }}
{{- end }}
