{{- if .Values.certManager.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.certManager.namespace }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: {{ .Values.certManager.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.certManager.releaseName }}
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.13.0
  values:
    replicaCount: {{ .Values.certManager.replicaCount }}
{{- if .Values.certManager.fake}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-cert-key
  namespace: {{ .Values.certManager.namespace }}
data:
  tls.crt: {{ .Values.ca.crt | b64enc | quote }}
  tls.key: {{ .Values.ca.key | b64enc | quote }}
{{- end}}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.certManager.namespace }}
spec:
  {{- if .Values.certManager.fake}}
  ca:
    secretName: ca-cert-key
  {{- else}}
  acme:
    server: {{ .Values.certManager.server | quote }}
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
  {{- end }}

{{- end }}
