{{- if .Values.certManager.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.certManager.namespace }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: {{ .Values.certManager.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.certManager.releaseName }}
  chart:
    repository: https://charts.jetstack.io
    name: cert-manager
    version: v0.13.0
  values:
    replicaCount: {{ .Values.certManager.replicaCount }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-issuer-keypair
  namespace: {{ .Values.certManager.namespace }}
data:
  tls.crt: {{ .Values.ca.crt | b64enc | quote }}
  tls.key: {{ .Values.ca.key | b64enc | quote }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: {{ .Values.certManager.namespace }}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: {{ .Values.certManager.email | quote }}
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ca-issuer
  namespace: {{ .Values.certManager.namespace }}
spec:
  ca:
    secretName: ca-issuer-keypair

{{- end }}
