{{- if .Values.dex.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.dex.namespace }}
---

{{ $redirectURI := printf "https://dex.%s/callback" .Values.hostedZone }}

apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: dex
  namespace: {{ .Values.dex.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.dex.releaseName }}
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: dex
    version: 2.5.0
  values:
    grpc: false
    ports:
      web:
        nodePort: {{ .Values.dex.port }}
        servicePort: {{ .Values.dex.port }}
    config:
      issuer: https://dex.{{ .Values.hostedZone }}
      connectors:
        {{- range .Values.auth }}
        - type: {{ .type | quote }}
          id: {{ .id | quote }}
          name: {{ .name | quote }}
          config:
            {{- with .oauth }}
            clientID: {{ .clientId | quote }}
            clientSecret: {{ .clientSecret | quote }}
            {{- end }}
            redirectURI: $redirectURI
            {{- if eq .type "github" }}
            {{- with .orgs }}
            orgs:
              {{- range . }}
              - name: {{ .name | quote }}
                {{- with .teams }}
                teams:
                  {{- range . }}
                  - {{ .name | quote }}
                  {{- end }}
                {{- end }}
              {{- end }}
            {{- end }}
            {{- else if eq .type "google" }}
            # TODO: Google-specific config goes here.
            {{- end }}
        {{- end }}
      staticClients:
        - id: {{ .Values.dex.oauth.clientId | quote }}
          name: {{ .Values.dex.oauth.clientId | quote }}
          secret: {{ .Values.dex.oauth.clientSecret | quote }}
          redirectURIs:
          - https://gangway.{{ .Values.hostedZone }}/callback
          trustedPeers:
            - {{ .Values.navigator.oauth.clientId | quote }}
            - {{ .Values.prometheusOperator.grafana.oauth.clientId | quote }}
            - {{ .Values.oauth2Proxy.oauth.clientId | quote }}
        - id: {{ .Values.navigator.oauth.clientId | quote }}
          name: {{ .Values.navigator.oauth.clientId | quote }}
          secret: {{ .Values.navigator.oauth.clientSecret | quote }}
          redirectURIs:
            - https://navigator.{{ .Values.hostedZone }}/kubernetes/auth/callback
        - id: {{ .Values.prometheusOperator.grafana.oauth.clientId | quote }}
          name: {{ .Values.prometheusOperator.grafana.oauth.clientId | quote }}
          secret: {{ .Values.prometheusOperator.grafana.oauth.clientSecret | quote }}
          redirectURIs:
            - https://grafana.{{ .Values.hostedZone }}/login/generic_oauth
        - id: {{ .Values.oauth2Proxy.oauth.clientId | quote }}
          name: {{ .Values.oauth2Proxy.oauth.clientId | quote }}
          secret: {{ .Values.oauth2Proxy.oauth.clientSecret | quote }}
          redirectURIs:
            - https://oauth2-proxy.{{ .Values.hostedZone }}/oauth2/callback
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - dex.{{ .Values.hostedZone }}
      tls:
        - secretName: dex-tls
          hosts:
            - dex.{{ .Values.hostedZone }}

{{- end }}
