{{- if .Values.gangway.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.gangway.namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-crt
  namespace: {{ .Values.gangway.namespace }}
data:
  ca.crt: {{ .Values.ca.crt | quote }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: gangway
  namespace: {{ .Values.gangway.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.gangway.releaseName }}
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: gangway
    version: 0.4.0
  values:
    extraVolumes:
      - name: ca-crt
        configMap:
          name: ca-crt
    extraVolumeMounts:
      - name: ca-crt
        mountPath: /etc/ca
        readOnly: true
    gangway:
      apiServerURL: {{ .Values.apiServerUrl | quote }}
      clusterName: {{ .Values.clusterName }}
      clientID: {{ .Values.dex.oauth.clientId | quote }}
      clientSecret: {{ .Values.dex.oauth.clientSecret | quote }}
      sessionKey: {{ randAlphaNum 32 | b64enc | quote }}
      authorizeURL: https://dex.{{ .Values.hostedZone }}/auth
      tokenURL: https://dex.{{ .Values.hostedZone }}/token
      audience: https://dex.{{ .Values.hostedZone }}/userinfo
      redirectURL: https://gangway.{{ .Values.hostedZone }}/callback
      trustedCAPath: /etc/ca/ca.crt
      scopes:
        - openid
        - profile
        - email
        - offline_access
        - groups
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - gangway.{{ .Values.hostedZone }}
      tls:
        - secretName: gangway-tls
          hosts:
            - gangway.{{ .Values.hostedZone }}

{{- end }}
