{{- if .Values.harbor.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.harbor.namespace }}
---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor
  namespace: {{ .Values.harbor.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.harbor.releaseName }}
  chart:
    repository: https://helm.goharbor.io
    name: harbor
    version: 1.3.1
  values:
    harborAdminPassword: {{ default (randAlphaNum 32) .Values.harbor.adminPassword | quote }}
    secretKey: {{ include "moondog.random16" .Values.harbor.secretKey | quote }}
    expose:
      ingress:
        hosts:
          core: harbor.{{ .Values.domainSuffix }}
          notary: harbor-notary.{{ .Values.domainSuffix }}
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: {{ .Values.certManager.defaultClusterIssuer | quote }}
      tls:
        notarySecretName: tls-harbor-notary-ingress
        secretName: tls-harbor-ingress
    externalURL: https://harbor.{{ .Values.domainSuffix }}
    persistence:
    {{- with .Values.harbor.persistence.imageChartStorage}}
      imageChartStorage:
        {{- toYaml . | nindent 8}}
    {{- else }}
      imageChartStorage: {}
    {{- end }}
    database:
      type: external
      external:
        host: harbor-pg
        username: {{ .Values.harbor.postgres.user }}
        password: {{ .Values.harbor.postgres.password | quote }}
    redis:
      type: external
      external:
        host: {{ .Values.harbor.releaseName }}-redis-redis-ha-haproxy

---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: harbor-redis
  namespace: {{ .Values.harbor.namespace }}
spec:
  timeout: {{ .Values.helmReleaseTimeout }}
  releaseName: {{ .Values.harbor.releaseName }}-redis
  chart:
    repository: https://dandydeveloper.github.io/charts
    name: redis-ha
    version: 4.5.3
  values:
    haproxy:
      enabled: true

{{- end }}
