{{- if and .Values.harbor.create .Values.kubedb.create }}

apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.harbor.namespace }}

---
apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: harbor-pg
  namespace: {{ .Values.harbor.namespace }}
spec:
  version: "10.6"
  replicas: 2
  standbyMode: Hot
  streamingMode: asynchronous
  storageType: "Durable"
  databaseSecret: 
    secretName: harbor-db-auth
  storage:
    storageClassName: aws-ebs-gp2
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1G
  init:
    scriptSource:
      configMap:
        name: harbor-init-sql
  backupSchedule:
    cronExpression: "@every 30m"
    storageSecretName: s3-credentials
    s3:
      endpoint: "s3.amazonaws.com"
      bucket: {{ .Values.kubedb.aws.s3_bucket }}
      prefix: harbor-pg
    podTemplate:
      spec:
        resources:
          requests:
            cpu: 100m
            memory: 256M
          limits:
            cpu: 500m
            memory: 1G
  podTemplate:
    spec:
      resources:
        requests:
          memory: 256M
          cpu: 250m
        limits:
          memory: 512M
          cpu: 1000m
  updateStrategy:
    type: RollingUpdate
  terminationPolicy: Pause

---
apiVersion: v1
kind: Secret
metadata:
  name: harbor-db-auth
  namespace: {{ .Values.harbor.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.harbor.postgres.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.harbor.postgres.user | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: {{ .Values.harbor.namespace }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.kubedb.aws.access_key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.kubedb.aws.access_key_secret | b64enc | quote }}

---
apiVersion: v1
data:
  harbor.sql: |
    CREATE DATABASE registry;
    CREATE DATABASE harbor;
    CREATE DATABASE core;
    CREATE DATABASE clair;
    CREATE DATABASE notary_server;
    CREATE DATABASE notary_signer;
kind: ConfigMap
metadata:
  name: harbor-init-sql
  namespace: {{ .Values.harbor.namespace }}
{{- end }}
